
    
    
    
      -- MySQL Script generated by MySQL Workbench
-- Mon Apr 11 09:40:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema flights
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flights
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flights` DEFAULT CHARACTER SET utf8 ;
USE `flights` ;
-- -----------------------------------------------------
-- Table `flights`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights`.`airport` (
  `code` VARCHAR(5) NOT NULL,
  `name` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `flights`.`gate`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights`.`gate` (
  `code` VARCHAR(3) NOT NULL,
  `desc` VARCHAR(45) NULL,
  PRIMARY KEY (`code`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `flights`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights`.`flight` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NOT NULL,
  `from_dttm` TIMESTAMP NOT NULL,
  `from_airport_code` VARCHAR(5) NOT NULL,
  `to_dttm` TIMESTAMP NOT NULL,
  `to_airport_code` VARCHAR(5) NOT NULL,
  `gate_code` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_flight_airport_idx` (`from_airport_code` ASC) VISIBLE,
  INDEX `fk_flight_airport1_idx` (`to_airport_code` ASC) VISIBLE,
  INDEX `fk_flight_gate1_idx` (`gate_code` ASC) VISIBLE,
  CONSTRAINT `fk_flight_airport`
    FOREIGN KEY (`from_airport_code`)
    REFERENCES `flights`.`airport` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_airport1`
    FOREIGN KEY (`to_airport_code`)
    REFERENCES `flights`.`airport` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_gate1`
    FOREIGN KEY (`gate_code`)
    REFERENCES `flights`.`gate` (`code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;